import type { Metadata } from "next";
import { Geist, Geist_Mono,Roboto } from "next/font/google";
import AuthProvider from "./auth/Provider";
import "./globals.css";
import NavBar from "./NavBar";
import GoogleAnalyticsScript from "./GoogleAnalyticsScript";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  subsets : ['latin'],
  weight : ["400" , "500"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // openGraph:{
  //   title : '...',
  //   description : '...'
  // }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="winter">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > 
      <GoogleAnalyticsScript />
        <AuthProvider>
        <NavBar/>
        <main className="p-5">{children}</main>
        </AuthProvider> 
      </body>
    </html>
  );
}


//this file is the root layout
//the nav bar will apply to all children since it is in root layout